screen:
  monitor: 1
  width: null
  height: null
rois:
  table:
    x: 284
    y: 230
    width: 1657
    height: 867
  my_hand:
    x: 0
    y: 0
    width: 0
    height: 0
  my_play_area:
    x: 0
    y: 0
    width: 0
    height: 0
  my_melds:
    x: 0
    y: 0
    width: 0
    height: 0
  left_melds:
    x: 0
    y: 0
    width: 0
    height: 0
  right_melds:
    x: 0
    y: 0
    width: 0
    height: 0
  top_melds:
    x: 0
    y: 0
    width: 0
    height: 0
  discards:
    x: 0
    y: 0
    width: 0
    height: 0
  drawn_tile:
    x: 0
    y: 0
    width: 0
    height: 0
  missing_suit:
    x: 0
    y: 0
    width: 0
    height: 0
  action_buttons:
    x: 0
    y: 0
    width: 0
    height: 0
